import Head from 'next/head'
import React from 'react'
import { FC } from 'react'
import Footer from './Footer'
import { ChildrenProps } from '../interfaces/Base'
import { Navbar } from './Navbar'
import styles from './MainLayout.module.css'

interface Props{
  children: any,
  title?: string
}

const MainLayout:FC<Props> = ({children, title}) => {

    return (
        <div className={styles.container}>
          <Head>
          <title>{title || 'Paliza'}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
            <meta name="keywords" content="prueba, test"></meta>
          </Head>
    
          <Navbar></Navbar>
    
          <main className={styles.main}>
            {children}
        </main>
        <Footer></Footer>
        </div>
      )
}

export default MainLayout